### ISSUE TITLE
Improvement on iterator

### ISSUE THREAD

**Issue by StefanWerW** [inoc603/node-red-contrib-yield#1]
Hello,

Improvement can be made here:

https://github.com/inoc603/node-red-contrib-yield/blob/master/yield.js#L16

Instead of map(), it's better to use forEach()

`msg.payload.forEach(function (message) {`

Have a nice one :smiley:

**Comment by inoc603** [comment]
Hi,

`forEach` is indeed faster than `map`, another nice trick learned! I fixed this in [this commit](https://github.com/inoc603/node-red-contrib-yield/commit/bbcb8e875d7f343aec93960f0b36c801f6a0b27f)

Thanks a lot!
